Repository kubermatic/bulward, pull requests merged in 2020-07, with the labels that each got.

#29 Setup proper .prow boilerplate (including e2e tests)
  .prow.yaml
  Makefile
  config/dockerfiles/test.Dockerfile
  hack/audit.yaml
  hack/e2e-test.sh
  hack/kind-config.yaml
  test/noop_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#28 Migrate Bulward to use github.com/kubermatic/utils
  go.mod
  go.sum
  pkg/internal/owner/doc.go
  pkg/internal/owner/owner.go
  pkg/internal/owner/owner_test.go
  pkg/internal/owner/reconcile.go
  pkg/internal/owner/reconcile_test.go
  pkg/internal/util/cmd.go
  pkg/internal/util/finalizer.go
  pkg/internal/util/finalizer_test.go
  pkg/internal/util/object.go
  pkg/internal/util/object_test.go
  pkg/internal/util/util_test.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#27 Added organization member's status support
  config/manager/crd/bases/bulward.io_organizations.yaml
  config/manager/rbac/role.yaml
  hack/codegen.sh
  pkg/apis/core/v1alpha1/organization_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/openapi/openapi_generated.go
  pkg/testutil/logger.go
  pkg/testutil/logger_test.go
  test/corev1alpha1_organization_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#23 Initial Organization implementation
  config/apiserver/rbac/role.yaml
  pkg/apis/apiserver/corev1alpha1.conversion.go
  pkg/apis/apiserver/organization_REST.go
  pkg/apis/apiserver/organization_unstructured_conversion.go
  pkg/apis/apiserver/zzz_fix_addtoschema.go
  pkg/apiserver/apiserver.go
  test/corev1alpha1_organization_test.go
  test/organization_test.go
  test/test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#26 Create project-admin and rbac-admin OrganizationRoletemplate for Organization owner
  config/manager/crd/bases/bulward.io_organizationroletemplates.yaml
  config/manager/crd/bases/bulward.io_organizations.yaml
  config/manager/crd/kustomization.yaml
  config/manager/rbac/role.yaml
  config/samples/organization.yaml
  pkg/apis/core/v1alpha1/organization_types.go
  pkg/apis/core/v1alpha1/organizationroletemplate_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/internal/controllers/organizationroletemplate_controller.go
  pkg/manager/manager.go
  pkg/openapi/openapi_generated.go
  pkg/templates/organizationrole.go
  test/corev1alpha1_organization_test.go
  test/organization_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#32 Add Pavel, Lukasz, Lovro as owners
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#30 E2E test improvement
  go.mod
  go.sum
  hack/e2e-test.sh
  test/apiserver_organization_test.go
  test/core_organization_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#35 fixed unnecessary go.mod version pinning
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#37 Upgrade go version to 1.14
  WORKSPACE
  go.mod
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#31 OrganizationRoleTemplate controller
  config/manager/crd/bases/bulward.io_organizationroletemplates.yaml
  config/manager/rbac/role.yaml
  pkg/apis/core/v1alpha1/organizationroletemplate_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/internal/controllers/organizationroletemplate_controller.go
  pkg/templates/organizationrole.go
  test/apiserver_organization_test.go
  test/storage_organization_test.go
  test/test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#39 Fix make test
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#34 Organization view filter
  pkg/apis/apiserver/organization_REST.go
  pkg/apis/apiserver/organization_unstructured_conversion.go
  test/apiserver_organization_test.go
  test/events/predicate.go
  test/events/tracer.go
  test/test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#44 Fix bugs in makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#40 Add goreleaser.
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#45 initial internal project
  config/manager/crd/bases/storage.bulward.io_projects.yaml
  config/manager/crd/kustomization.yaml
  config/manager/rbac/role.yaml
  go.sum
  pkg/apis/storage/v1alpha1/project_types.go
  pkg/apis/storage/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/internal/controllers/extractors.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/internal/controllers/project_controller.go
  pkg/manager/manager.go
  pkg/openapi/openapi_generated.go
  test/storage_project_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#43 Organization owners should be the only ones with edit privileges
  Makefile
  config/apiserver/rbac/kustomization.yaml
  config/apiserver/rbac/user_clusterrole.yaml
  config/apiserver/rbac/user_clusterrolebinding.yaml
  pkg/apis/apiserver/organization_REST.go
  test/apiserver_organization_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#50 Propagate members from Project to Organization
  pkg/manager/internal/controllers/extractors.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/internal/controllers/project_controller.go
  test/storage_organization_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#49 Implement namespace cleanup for Project
  .pre-commit-config.yaml
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/internal/controllers/project_controller.go
  test/storage_project_test.go
  test/test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#52 Use conversion-gen in codegen.sh
  boilerplate.go.txt
  hack/codegen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#53 Add dev image
  Makefile
  config/dockerfiles/dev.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#54 Fix make generate in dev image
  Makefile
  config/dockerfiles/dev.Dockerfile
  hack/codegen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#48 Create Roles/RoleBindings for Organization Owner in Project namespace.
  pkg/manager/internal/controllers/organizationroletemplate_controller.go
  pkg/templates/organizationrole.go
  test/apiserver_organization_test.go
  test/storage_organization_test.go
  test/storage_project_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#61 Using Kubermatic-lab boilerplate
  .pre-commit-config.yaml
  config/dockerfiles/test.Dockerfile
  go.mod
  hack/boilerplate/boilerplate.go
  hack/boilerplate/boilerplate_test.go
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
  hack/verify-boilerplate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
