Repository kubermatic/bulward, pull requests merged in 2020-06, with the labels that each got.

#1 Add initial concept for bulward
  docs/concept.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#9 Add logo
  README.md
  docs/img/Bulward.png
  docs/img/Bulward.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#8 Add Prow jobs
  .prow.yaml
  Makefile
  docs/concept.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3 Project Boilerplate
  .prow.yaml
  Makefile
  cmd/manager/main.go
  config/dockerfiles/manager.dockerfile
  config/dockerfiles/test.Dockerfile
  config/manager/certmanager/certificate.yaml
  config/manager/certmanager/kustomization.yaml
  config/manager/certmanager/kustomizeconfig.yaml
  config/manager/default/kustomization.yaml
  config/manager/default/manager_webhook_patch.yaml
  config/manager/default/webhookcainjection_patch.yaml
  config/manager/manager/kustomization.yaml
  config/manager/manager/manager.yaml
  config/manager/prometheus/kustomization.yaml
  config/manager/prometheus/monitor.yaml
  config/manager/rbac/kustomization.yaml
  config/manager/rbac/leader_election_role.yaml
  config/manager/rbac/leader_election_role_binding.yaml
  config/manager/rbac/role_binding.yaml
  config/manager/webhook/kustomization.yaml
  config/manager/webhook/kustomizeconfig.yaml
  config/manager/webhook/service.yaml
  go.mod
  go.sum
  hack/boilerplate/boilerplate.go
  hack/codegen.sh
  hack/start-docker.sh
  hack/validate-directory-clean.sh
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#11 Fix the generated files path
  hack/codegen.sh
Labels: approved, dco-signoff: yes, release-note-none, size/S

#12 Init Internal Organization
  Makefile
  config/dockerfiles/manager.Dockerfile
  config/dockerfiles/test.Dockerfile
  config/manager/crd/bases/bulward.io_internalorganizations.yaml
  config/manager/crd/kustomization.yaml
  config/manager/default/kustomization.yaml
  config/manager/manager/manager.yaml
  config/manager/rbac/kustomization.yaml
  config/manager/rbac/leader_election_role_binding.yaml
  config/manager/rbac/role.yaml
  config/manager/rbac/role_binding.yaml
  config/manager/rbac/service_account.yaml
  config/samples/internalorganization.yaml
  go.mod
  go.sum
  pkg/apis/core/v1alpha1/groupversion_info.go
  pkg/apis/core/v1alpha1/internalorganization_types.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/owner/doc.go
  pkg/internal/owner/owner.go
  pkg/internal/owner/owner_test.go
  pkg/internal/owner/reconcile.go
  pkg/internal/owner/reconcile_test.go
  pkg/internal/util/cmd.go
  pkg/internal/util/finalizer.go
  pkg/internal/util/finalizer_test.go
  pkg/internal/util/object.go
  pkg/internal/util/object_test.go
  pkg/internal/util/util_test.go
  pkg/manager/internal/controllers/internalorganization_controller.go
  pkg/manager/manager.go
  pkg/testutil/logger.go
  pkg/testutil/logger_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#22 Bootstrap API Extension Server
  .gitignore
  BUILD.bazel
  Makefile
  PROJECT
  WORKSPACE
  boilerplate.go.txt
  cmd/apiserver/main.go
  config/apiserver/certmanager/certificate.yaml
  config/apiserver/certmanager/kustomization.yaml
  config/apiserver/certmanager/kustomizeconfig.yaml
  config/apiserver/default/kustomization.yaml
  config/apiserver/default/manager_webhook_patch.yaml
  config/apiserver/default/webhookcainjection_patch.yaml
  config/apiserver/manager/apiservice.yaml
  config/apiserver/manager/kustomization.yaml
  config/apiserver/manager/kustomizeconfig.yaml
  config/apiserver/manager/manager.yaml
  config/apiserver/manager/service.yaml
  config/apiserver/prometheus/kustomization.yaml
  config/apiserver/prometheus/monitor.yaml
  config/apiserver/rbac/extension_apiserver_auth_role_binding.yaml
  config/apiserver/rbac/kustomization.yaml
  config/apiserver/rbac/leader_election_role.yaml
  config/apiserver/rbac/leader_election_role_binding.yaml
  config/apiserver/rbac/role.yaml
  config/apiserver/rbac/role_binding.yaml
  config/apiserver/rbac/service_account.yaml
  config/apiserver/webhook/kustomization.yaml
  config/apiserver/webhook/kustomizeconfig.yaml
  config/apiserver/webhook/service.yaml
  config/dockerfiles/apiserver.Dockerfile
  config/manager/manager/manager.yaml
  docs/examples/organization/organization.yaml
  go.mod
  go.sum
  hack/codegen.sh
  pkg/apis/apiserver/doc.go
  pkg/apis/apiserver/install/doc.go
  pkg/apis/apiserver/install/zz_generated.api.register.go
  pkg/apis/apiserver/organization_REST.go
  pkg/apis/apiserver/organization_strategy.go
  pkg/apis/apiserver/v1alpha1/doc.go
  pkg/apis/apiserver/v1alpha1/organization_types.go
  pkg/apis/apiserver/v1alpha1/zz_generated.api.register.go
  pkg/apis/apiserver/v1alpha1/zz_generated.conversion.go
  pkg/apis/apiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apiserver/v1alpha1/zz_generated.defaults.go
  pkg/apis/apiserver/zz_generated.api.register.go
  pkg/apis/apiserver/zz_generated.deepcopy.go
  pkg/apis/apiserver/zz_generated.defaults.go
  pkg/apis/doc.go
  pkg/apis/zz_generated.api.register.go
  pkg/apiserver/apiserver.go
  pkg/openapi/doc.go
  pkg/openapi/openapi_generated.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#24 Rename InternalOrganization to Organization
  config/manager/crd/bases/bulward.io_organizations.yaml
  config/manager/crd/kustomization.yaml
  config/manager/rbac/role.yaml
  config/samples/organization.yaml
  pkg/apis/core/v1alpha1/organization_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/internal/controllers/internalorganization_controller.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL
