Repository kubermatic/bulward, pull requests merged in 2020-08, with the labels that each got.

#65 extracted common org-project ownership methods
  pkg/apis/apiserver/organization_REST.go
  pkg/apis/apiserver/ownership.go
  pkg/apis/apiserver/project_REST.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#62 Use vanity import k8c.io/bulward
  .pre-commit-config.yaml
  BUILD.bazel
  Makefile
  PROJECT
  cmd/apiserver/main.go
  cmd/manager/main.go
  go.mod
  hack/codegen.sh
  pkg/apis/apiserver/doc.go
  pkg/apis/apiserver/install/zz_generated.api.register.go
  pkg/apis/apiserver/organization_REST.go
  pkg/apis/apiserver/organization_unstructured_conversion.go
  pkg/apis/apiserver/project_REST.go
  pkg/apis/apiserver/project_unstructured_conversion.go
  pkg/apis/apiserver/storagev1alpha1.conversion.go
  pkg/apis/apiserver/v1alpha1/doc.go
  pkg/apis/apiserver/v1alpha1/generated.pb.go
  pkg/apis/apiserver/v1alpha1/generated.proto
  pkg/apis/apiserver/v1alpha1/organization_types.go
  pkg/apis/apiserver/v1alpha1/project_types.go
  pkg/apis/apiserver/v1alpha1/zz_generated.api.register.go
  pkg/apis/apiserver/v1alpha1/zz_generated.conversion.go
  pkg/apis/apiserver/zz_generated.api.register.go
  pkg/apis/apiserver/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/doc.go
  pkg/apis/storage/v1alpha1/doc.go
  pkg/apis/storage/v1alpha1/generated.pb.go
  pkg/apis/storage/v1alpha1/generated.proto
  pkg/apis/zz_generated.api.register.go
  pkg/apiserver/apiserver.go
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/internal/controllers/organizationroletemplate_controller.go
  pkg/manager/internal/controllers/project_controller.go
  pkg/manager/internal/controllers/projectroletemplate_controller.go
  pkg/manager/manager.go
  pkg/openapi/openapi_generated.go
  pkg/templates/organizationrole.go
  test/apiserver_organization_test.go
  test/apiserver_project_test.go
  test/storage_organization_test.go
  test/storage_project_test.go
  test/test.go
Labels: approved, dco-signoff: yes, release-note-none, size/XXL

#63 Use vanity import k8c.io/utils
  go.mod
  go.sum
  pkg/manager/internal/controllers/organization_controller.go
  pkg/manager/internal/controllers/project_controller.go
  pkg/manager/internal/controllers/projectroletemplate_controller.go
  pkg/manager/manager.go
  test/apiserver_organization_test.go
  test/storage_organization_test.go
  test/storage_project_test.go
  test/test.go
Labels: approved, dco-signoff: yes, release-note-none, size/M

#67 Increase make generate performance on Mac by using delegated mount mode
  Makefile
Labels: approved, dco-signoff: yes, release-note-none, size/XS
